server:
  port: 8181

jira:
  url: "https://jira.unidata-platform.com"
  project: "DM"
  auth:
    basic: "Basic TW9ya292a0E6bXlTdXBlclBhc3M="
  comment:
    test:
      case:
        start: "Сценарий для тестирования на препроде"
    deploy:
      instruction:
        start: "Инструкция по установке"