jira:
  url: "https://jira.unidata-platform.com"
  auth:
    basic: "Basic TW9ya292a0E6bXlTdXBlclBhc3M="
  search:
    default:
      project: "DM"
      limit: 15
      comment:
        test:
          case:
            start: "Сценарий для тестирования на препроде"
        deploy:
          instruction:
            start: "Инструкция по установке"