jira:
  url: "https://jira.unidata-platform.com"
  auth:
    basic: ${JIRA_AUTH_BASIC:Basic ZGVuaXMuZ2x1c2hrb3Y6RDUyMjU5OHo=} #TW9ya292a0E6bXlTdXBlclBhc3M=
  search:
    default:
      project: "DM"
      limit: 15
      comment:
        test:
          case:
            start: "Сценарий для тестирования на препроде"
            paragraph: ""
            default: ""
        deploy:
          instruction:
            start: "Инструкция по установке"
        new:
          functions:
            start: "Новые функции и исправления"
            paragraph: ""
            default: "Новых функций не найдено"
        dataBase:
          changes:
            start: "Настройка и измененя в структуре БД, атрибутах, справочниках"
            paragraph: ""
            default: ""
        configs:
          start: "Конфигурация"
          paragraph: ""
          default: "Конфигурация в нынешней версии не изменена"
        settings:
          changes:
            start: "Порядок установки и изменения настроек"
            paragraph: ""
            default: "Порядок установка и изменения настроек не обнаружены"
        testing:
          plan:
            start: "План тестирования"
            paragraph: ""
            default: "Прогнать быстрые тесты"
        rollback:
          plan:
            start: "План отката"
            paragraph: ""
            default: "Откатить обновленные артефакты на предыдущие версии."


auth:
  encoder:
    strength: ${ENCODER_STRENGTH:5}
  valid:
    token: ${TOKEN:0}
