jira:
  url: "https://jira.unidata-platform.com"
  auth:
    basic: ${JIRA_AUTH_BASIC:Basic ZGVuaXMuZ2x1c2hrb3Y6RDUyMjU5OHo=} #TW9ya292a0E6bXlTdXBlclBhc3M=
  search:
    default:
      project: "DM"
      limit: 15
      comment:
        test:
          case:
            start: "Сценарий для тестирования на препроде"
            paragraph: ""
            default: ""
        deploy:
          instruction:
            start: "Инструкция по установке"

auth:
  encoder:
    strength: ${ENCODER_STRENGTH:5}
  valid:
    token: ${TOKEN:0}

constant:
  dbChanges: "БД:\n"
  dbChangesEmpty: "Настройки и изменения в структуре БД, атрибутах, справочниках"
  configs: "Конфигурация:\n"
  configsEmpty: "Конфигурация"
  installation: "Установка:\n"
  installationEmpty: "Порядок установок и изменения настроек"
  testing: "Тестирование:\n"
  testingEmpty: "План тестирования"
  rollback: "Откат:\n"
  rollbackEmpty: "План отката"
