jira:
  url: "https://jira.unidata-platform.com"
  auth:
    basic: ${JIRA_AUTH_BASIC:Basic TW9ya292a0E6bXlTdXBlclBhc3M=}
  search:
    default:
      project: "DM"
      limit: 15
      comment:
        test:
          case:
            start: "Сценарий для тестирования на препроде"
        deploy:
          instruction:
            start: "Инструкция по установке"

auth:
  encoder:
    strength: ${ENCODER_STRENGTH:5}
  valid:
    token: ${TOKEN:0}