server:
  port : 8080

auth:
  encoder:
    strength: ${ENCODER_STRENGTH:5}
  valid:
    token: ${TOKEN:0}

jira:
  url: "https://jira.unidata-platform.com"
  auth:
    basic: ${JIRA_AUTH_BASIC:Basic TW9ya292a0E6bXlTdXBlclBhc3M}
  paragraph:
    font:
      size: "h1. "
  start:
    font:
      size: "h2. "
  release:
    offline-merge:
      name: "offline-merge"
      sources: "_Исходные коды_:\n
  * https://host:port/-/tree/vXXXXX"
    kzd2:
      name: "kzd2"
      sources: "_Исходные коды_:\n
  * https://host:port/-/tree/vXXXXX"
    ksrd:
      name: "ksrd"
      sources: "_Исходные коды_:\n
  * https://host:port/-/tree/vXXXXX"
  search:
    default:
      limit: 15
      task:
        paragraph: "${jira.paragraph.font.size}*Ресурсы*"
        in:
          start: "Релиз "
          paragraph: "_Задача в Jira:_"
      comment:
        source-code:
          start: "${jira.start.font.size}Исходные коды:"
          paragraph: "_Исходные коды:_"
          default: ${SOURCE_CODE:*{color:#FF0000}Не заполнено.{color}*}
        artifact:
          start: "${jira.start.font.size}Артефакты:"
          paragraph: "${jira.paragraph.font.size}*Артефакты*"
          default: ${STORAGE_LINK:*{color:#FF0000}Не заполнено.{color}*}
        new-feature:
          start: "${jira.start.font.size}Новые функции и исправления:"
          paragraph: "${jira.paragraph.font.size}*Новые функции и исправления*"
          paragraph_external: "${jira.paragraph.font.size}*Новые функции и исправления (Версия для заказчика)*"
          default: "*{color:#FF0000}Не заполнено{color}*"
        deploy-instruction:
          start: "${jira.start.font.size}Порядок установки:"
          paragraph: "${jira.paragraph.font.size}*Порядок установки и изменения настроек*"
          default: "*{color:#FF0000}Не заполнено{color}*"
        test-case:
          start: "${jira.start.font.size}План тестирования у заказчика:"
          paragraph: "${jira.paragraph.font.size}*План тестирования*"
          default: "Выполнить соответствующие быстрые тесты для релиза"
        rollback-action:
          start: "${jira.start.font.size}План отката:"
          paragraph: "${jira.paragraph.font.size}*План отката*"
          default: "Откатить обновленные артефакты на предыдущие версии"

# deprecated
        database-change:
          start: "${jira.start.font.size}Настройки и изменения в структуре БД, атрибутах, справочниках:"
          paragraph: "${jira.paragraph.font.size}*Настройки и изменения в структуре БД, атрибутах, справочниках*"
          default: "Не требуется"
        monitoring-change:
          start: "${jira.start.font.size}Информация для подключений и мониторинга:"
          paragraph: "${jira.paragraph.font.size}*Информация для подключений и мониторинга*"
          default: "Не требуется"
        config:
          start: "${jira.start.font.size}Конфигурация:"
          paragraph: "${jira.paragraph.font.size}*Конфигурация*"
          default: "Не требуется"